base:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  devmemoryLimits: "1536Mi"
  devmemoryRequests: "768Mi"
  devcpuLimits: "500m"
  devcpuRequests: "250m"
  environment:
    DYNATRACE_UI_TRACKING_ID: "bf24054dsx/4bf1f9dd4856af92"
